In [1]:
import pandas as pd
import yfinance as yf
from yahoofinancials import YahooFinancials
import pandas_datareader as web
import numpy as np

In [2]:
tickers = ["AAPL","GOOGL","AMZN", "NKE"]
multpl_stocks = web.get_data_yahoo(tickers,
start = "2021-09-01",
end = "2021-10-01")

In [3]:
multpl_stocks["Open"]

Symbols           AAPL        GOOGL         AMZN         NKE
Date
2021-09-01  152.830002  2900.000000  3496.399902  164.919998
2021-09-02  153.869995  2904.320068  3494.760010  165.240005
2021-09-03  153.759995  2861.610107  3452.000000  163.199997
2021-09-07  154.970001  2876.689941  3478.000000  163.699997
2021-09-08  156.979996  2882.000000  3511.649902  162.000000
2021-09-09  155.490005  2876.810059  3526.020020  165.259995
2021-09-10  155.000000  2884.250000  3501.830078  164.250000
2021-09-13  150.630005  2838.989990  3482.800049  161.559998
2021-09-14  150.350006  2859.909912  3475.550049  159.169998
2021-09-15  148.559998  2855.429932  3442.520020  157.500000
2021-09-16  148.440002  2879.010010  3459.959961  157.589996
2021-09-17  148.820007  2860.610107  3488.409912  157.960007
2021-09-20  143.800003  2763.229980  3396.000000  153.729996
2021-09-21  143.929993  2794.989990  3375.000000  155.089996
2021-09-22  144.449997  2786.080078  3351.000000  156.789993
2021-09-23  146.649994  2819.750000  3380.050049  158.710007
2021-09-24  145.660004  2810.770020  3402.010010  151.039993
2021-09-27  145.470001  2816.090088  3371.500000  149.509995
2021-09-28  143.250000  2773.100098  3357.709961  147.339996
2021-09-29  142.470001  2739.600098  3322.110107  145.710007
2021-09-30  143.660004  2685.229980  3316.000000  145.880005
2021-10-01  141.899994  2688.949951  3289.010010  145.220001

In [4]:
portfolio_returns = multpl_stocks["Open"].pct_change()

In [5]:
portfolio_returns.head(10)

Symbols         AAPL     GOOGL      AMZN       NKE
Date
2021-09-01       NaN       NaN       NaN       NaN
2021-09-02  0.006805  0.001490 -0.000469  0.001940
2021-09-03 -0.000715 -0.014706 -0.012235 -0.012346
2021-09-07  0.007869  0.005270  0.007532  0.003064
2021-09-08  0.012970  0.001846  0.009675 -0.010385
2021-09-09 -0.009492 -0.001801  0.004092  0.020123
2021-09-10 -0.003151  0.002586 -0.006860 -0.006112
2021-09-13 -0.028194 -0.015692 -0.005434 -0.016377
2021-09-14 -0.001859  0.007369 -0.002082 -0.014793
2021-09-15 -0.011906 -0.001566 -0.009504 -0.010492

In [6]:
#On initialise des poids au hasard (qui seront optimisés par la suite)
weight_portfolio = [0.1, 0.5, 0.3, 0.7]
return_port = portfolio_returns.dot(weight_portfolio)
return_port.head(10)

Date
2021-09-01         NaN
2021-09-02    0.002643
2021-09-03   -0.019737
2021-09-07    0.007826
2021-09-08   -0.002147
2021-09-09    0.013464
2021-09-10   -0.005358
2021-09-13   -0.023760
2021-09-14   -0.007481
2021-09-15   -0.012169
dtype: float64

In [7]:
#Matrice de covariance
covariance_matrix = portfolio_returns.cov()*252
covariance_matrix

Symbols      AAPL     GOOGL      AMZN       NKE
Symbols
AAPL     0.037635  0.021793  0.017876  0.022084
GOOGL    0.021793  0.033338  0.015239  0.018029
AMZN     0.017876  0.015239  0.020107  0.009480
NKE      0.022084  0.018029  0.009480  0.055921

In [10]:
# Calcul de la variance du portefeuille
portfolio_variance = np.transpose(weight_portfolio)@covariance_matrix@weight_portfolio
portfolio_variance

0.06543918030160979

In [11]:
# Calcul de la volatilité (risque)
portfolio_volatility = np.sqrt(portfolio_variance)
print("Portfolio Variance is", portfolio_variance)
print("Portfolio Volatility is", portfolio_volatility)

Portfolio Variance is 0.06543918030160979
Portfolio Volatility is 0.2558108291327984